apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-gpu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SJoon99/Sandbox
    targetRevision: main
    path: argocd/jupyter-gpu
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

